---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: infraenv-300-cars-lab
  namespace: 300-cars-lab
spec:
  additionalNTPSources:
    - registry.cars.lab
    - fd00:6:6:11::52
  clusterRef:
    name: 300-cars-lab
    namespace: 300-cars-lab
  ## (optional pub key)
  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk='
  agentLabelSelector:
    matchLabels:
      cluster-name: 300-cars-lab
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #proxy:
  #  httpProxy: http://infra-registry.infra.cars.lab:3128
  #  httpsProxy: http://infra-registry.infra.cars.lab:3128
  #  noProxy: .cars.lab
  # Modify ignition during discovery
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  ## Custom network configuration
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: 300-nmstate
