---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml

generators:
# This is common to all RAN deployments
#- common-policies/common-ranGen.yaml
# This group policy is for all Dell EMC XR12 based deployments:
- group-policies/group-xr12.yaml
# This group validator policy is for all Dell EMC XR12 based deployments:
- group-policies/group-xr12-validator.yaml
# This group policy is for all compressed 3-node cluster deployments:
#- group-du-3node-ranGen.yaml
# This group validator policy is for all compressed 3-node cluster deployments:
#- group-du-3node-validator-ranGen.yaml
# This group policy is for all standard cluster deployments:
#- group-du-standard-ranGen.yaml
# This group validator policy is for all standard cluster deployments:
#- group-du-standard-validator-ranGen.yaml
# These are examples that should be replicated for every individual site:
- site-specific-policies/flexranicx-cars2-lab.yaml
#- example-multinode-site.yaml
# These are cluster specific policies:
- cluster-specific-policies/gnb-flexranicx-cars2-lab.yaml
