---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name:  worker-flex10
  labels:
    machineconfiguration.openshift.io/role: worker-flex10
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker, worker-flex10]
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-flex10: ""
