# gnb-flexrankepler-cars2-lab-bmc-secret & assisted-deployment-pull-secret need to be created under same namespace flexrankepler
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "gnb-flexrankepler-cars2-lab"
  namespace: "gnb-flexrankepler-cars2-lab"
spec:
  baseDomain: "cars2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.12.10-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
  - clusterName: "flexrankepler"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ~/site-policies:
      # ../../../site-policies/common-policies/common-ranGen.yaml will apply to all clusters with 'common-du: true'
      common-du: true
      # ../../../site-policies/common-policies/group-hook-flexrankepler.yaml will apply to all clusters with 'flexrankepler-group-hook: ""'
      flexrankepler-group-smcx12: ""
      # ../../../site-policies/site-specific-policies/flexrankepler-cars2-lab.yaml will apply to all clusters with 'sites : "flexrankepler-cars2-lab"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "flexrankepler-cars2-lab"
      kepler: true
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      - cidr: fd01::/48
        hostPrefix: 64
    machineNetwork:
      - cidr: 192.168.38.128/26
      - cidr: 2600:52:7:300::0/64
    serviceNetwork:
      - 172.30.0.0/16
      - fd02::/112
    additionalNTPSources:
      - clock.cars2.lab
      - clock-v6.cars2.lab
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "gnb-kepler.flexrankepler.cars2.lab"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia://192.168.38.200/redfish/v1/Systems/1/"
        bmcCredentialsName:
          name: "gnb-flexrankepler-cars2-lab-bmc-secret"
        bootMACAddress: "3c:ec:ef:b6:ce:f2"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/nvme0n1"
        cpuset: "0-1,32-33"
        ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"storage":{"disks":[{"device":"/dev/nvme0n1","partitions":[{"label":"root","number":4,"resize":true,"sizeMiB":70000},{"label":"lso_75G_1","sizeMiB":75000},{"label":"lso_75G_2","sizeMiB":75000}],"wipeTable":false}]}}'
        nodeNetwork:
          interfaces:
            - name: eno5
              macAddress: "3c:ec:ef:b6:ce:f2"
            - name: eno6
              macAddress: "3c:ec:ef:b6:ce:f3"
            - name: enp81s0f0
              macAddress: "50:7c:6f:30:fb:e8"
            - name: enp81s0f1
              macAddress: "50:7c:6f:30:fb:e9"
            - name: enp81s0f2
              macAddress: "50:7c:6f:30:fb:ea"
            - name: enp81s0f3
              macAddress: "50:7c:6f:30:fb:eb"
          config:
            interfaces:
            - name: eno5
              type: ethernet
              state: up
              ipv4:
                enabled: true
                address:
                  - ip: "192.168.38.142"
                    prefix-length: 26
                dhcp: false
              ipv6:
                enabled: true
                address:
                  - ip: "2600:52:7:300::142"
                    prefix-length: 64
                autoconf: false
                dhcp: false
            - name: eno6
              type: ethernet
              state: down
            - name: enp81s0f0
              type: ethernet
              state: down
            - name: enp81s0f1
              type: ethernet
              state: down
            - name: enp81s0f2
              type: ethernet
              state: down
            - name: enp81s0f3
              type: ethernet
              state: down
            dns-resolver:
              config:
                server:
                  - 192.168.38.12
                  - 2600:52:7:38::12
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.38.129
                next-hop-interface: eno5
              - destination: ::/0
                next-hop-address: 2600:52:7:300::1
                next-hop-interface: eno5
