# Validate CPU topology
# for file in /sys/devices/system/cpu/cpu[0-9]*/topology/thread_siblings_list; do cat $file; done |sort -k2 -n | uniq | sort -V
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-fec1-smci01-profile0
spec:
  additionalKernelArgs:
  - rcupdate.rcu_normal_after_boot=0
  - crashkernel=512M
  - slub_debug=FZPU
  cpu:
    isolated: 4-23,28-47
    reserved: 0-3,24-27
  net:
    userLevelNetworking: true
    #devices:
    # intel I350
    #- interfaceName: eno*
    # intel X550
    #- interfaceName: enp25s0*
    # silicom sts
    #- interfaceName: enp138s0*
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/master: ""
