---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: fec1

resources:
  - 01-pao-ran-du-fec1-smci01-profile0.yaml
  #- 02-node-labels.yaml
  #- 03-node-labels.yaml
