---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super1-hub-cars-lab
  namespace: hub-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super2-hub-cars-lab
  namespace: hub-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-super3-hub-cars-lab
  namespace: hub-cars-lab
data:
  username: cm9vdA==
  password: YWx0aW9zdGFyMTIz
type: Opaque
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super1-hub-cars-lab
  namespace: hub-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-hub-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super1"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: 52:52:00:11:22:11
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://10.40.0.241:8000/redfish/v1/Systems/50279a5d-fd93-401b-8575-1e8ccea21f23
    credentialsName: bmc-super1-hub-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super2-hub-cars-lab
  namespace: hub-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-hub-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super2"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: 52:52:00:11:22:22
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://10.40.0.241:8000/redfish/v1/Systems/61574ce2-0c42-4197-b1e6-590f552a49c5
    credentialsName: bmc-super2-hub-cars-lab
    disableCertificateVerification: True
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: super3-hub-cars-lab
  namespace: hub-cars-lab
  labels:
    infraenvs.agent-install.openshift.io: "infraenv-hub-cars-lab"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "super3"
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/installer-args: '["--copy-network"]'
spec:
  online: true
  bootMACAddress: 52:52:00:11:22:33
  automatedCleaningMode: disabled
  bmc:
    address: redfish-virtualmedia+http://10.40.0.241:8000/redfish/v1/Systems/06e029f1-2122-40dc-8358-8dee200cb420
    credentialsName: bmc-super3-hub-cars-lab
    disableCertificateVerification: True
