---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: wrangler-cars-lab
  namespace: wrangler-cars-lab
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
