---
apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: infraenv-wrangler-cars-lab
  namespace: wrangler-cars-lab
spec:
  additionalNTPSources:
    - registry.cars.lab
    - fd00:6:6:11::52
  clusterRef:
    name: wrangler-cars-lab
    namespace: wrangler-cars-lab
  ## (optional pub key)
  sshAuthorizedKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdbJDYY43Zu0EKAGgrSKEobyXIxdhT0AeTT3yBoNY+YdYDScimJsQzK4hKNJIn1xC3klr0dSnsqeJru+SA4GMhbdcsmVyudhutCw75R/vFoRHOwaeVS2SMiBAtDbAYGQ3dh6LapkmXeLURcycNbebUV4HM9XsYqnuL8J2XyY4tRKgHrAd6OQw4jsXDOxwTRlHM822N/2kgv8iEwiXAJoUoymbr8mnfSxuuaH0oiKBwuaK1wuaDrlJyXkXNslPq89/1f8hJfjixY2dQdW7Xk5m3t5ptQxWENpw79OMRJ4cDW4G7LrtFONom5KQ+9TBZJIhNgJobkqI4qwinrWF8qMW5'
  agentLabelSelector:
    matchLabels:
      cluster-name: wrangler-cars-lab
  pullSecretRef:
    name: assisted-deployment-pull-secret
  #proxy:
  #  httpProxy: http://infra-registry.infra.cars.lab:3128
  #  httpsProxy: http://infra-registry.infra.cars.lab:3128
  #  noProxy: .cars.lab
  # Modify ignition during discovery
  #ignitionConfigOverride: '{"ignition": {"version": "3.1.0"}, "storage": {"files": [{"path": "/etc/someconfig", "contents": {"source": "data:text/plain;base64,aGVscGltdHJhcHBlZGluYXN3YWdnZXJzcGVj"}}]}}'
  ## Custom network configuration
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: wrangler-nmstate
