#oc create secret generic assisted-deployment-pull-secret -n c3-cars-lab --from-file=.dockerconfigjson=/home/user/pull-secret-fun/pull-secret-combined.json --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  .dockerconfigson: FILL IN HERE
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: c3-cars-lab
type: kubernetes.io/dockerconfigjson
