---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: c3-cars-lab
  namespace: c3-cars-lab
spec:
  baseDomain: cars.lab
  clusterName: c3
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: c3-cars-lab
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "c3-cars-lab"
  pullSecretRef:
    name: assisted-deployment-pull-secret
