---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: unload-drm-console-modules
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modprobe.d/drm-blacklist.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:,
