#oc create secret generic assisted-deployment-pull-secret -n skylark-cars-lab --from-file=.dockerconfigjson=/home/dcain/pull-secret-fun/pull-secret-combined.json --type=kubernetes.io/dockerconfigjson
--
apiVersion: v1
data:
  .dockerconfigson: FILL IN HERE      
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: skylark-cars-lab
type: kubernetes.io/dockerconfigjson
